project: 
  type: website
  execute-dir: file
  output-dir: ../docs

execute: 
  cache: false
  warning: false
  message: false

format:
  html:
    theme: lux
    toc: true
    toc-depth: 3
    standalone: true
    embed-resources: true
    
website:
  page-navigation: true
  navbar:
    search: true
    left:
      - text: "Home"
        file: 00-home.qmd
      - text: "Setup"
        file: 00-setup.qmd
      - sidebar:imaging
      - sidebar:spots 
  sidebar:
    - id: imaging 
      title: "Imaging-based Analysis"
      style: "docked"
      background: light
      collapse-level: 3
      contents: 
        - text: "---"
        - text: "Univariate Methods"
        - text: "---"
        - text: "Univariate Point Pattern Methods"
          file: 01-within-marks.qmd
        - text: "Univariate Lattice Methods"
          file: 03-irregular-lattices.qmd
        - text: "---"
        - text: "Multivariate Methods"
        - text: "---"
        - text: "Multivariate Point Pattern Methods"
          file: 02-between-marks.qmd
        - text: "Multivariate Lattice Methods"
          
    - id: spots
      title: "Spot-based Analysis"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - text: "Spots"
          file: 04-spotbased.qmd