project: 
  type: website
  execute-dir: file
  output-dir: ../docs

bibliography: ../misc/PASTA.bib

execute: 
  cache: false
  warning: false
  message: false

format:
  html:
    theme: lux
    toc: true
    toc-depth: 3
    standalone: true
    embed-resources: true
    code-fold: true
    code-summary: "Show the code"
    
editor_options: 
  chunk_output_type: console

website:
  page-navigation: true
  navbar:
    search: true
    left:
      - text: "Home"
        file: 00-home.qmd
      - text: "Setup"
        file: 00-setup.qmd
      - sidebar:cellbased
      - sidebar:spotbased
  sidebar:
    - id: cellbased 
      title: "Cell-based Analysis"
      style: "docked"
      background: light
      collapse-level: 3
      contents: 
        - text: "---"
        - text: "Univariate Methods"
        - text: "---"
        - text: "Univariate Point Pattern Methods"
          file: 01-cell-univar-point.qmd
        - text: "Univariate Lattice Methods for Cells"
          file: 02-cell-univar-lattice.qmd
        - text: "---"
        - text: "Multivariate Methods"
        - text: "---"
        - text: "Multivariate Point Pattern Methods"
          file: 03-cell-multivar-point.qmd
        - text: "Multivariate Lattice Methods for Cells"
          file: 04-cell-multivar-lattice.qmd
          
    - id: spotbased
      title: "Spot-based Analysis"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - text: "Univariate Lattice Methods for Spots"
          file: 05-spot-univar-lattice.qmd
        - text: "Multivariate Lattice Methods for Spots"
          file: 06-spot-multivar-lattice.qmd